In [1]:

filepath = 'sample_esp_fixed.txt'  
a= []
with open(filepath) as fp:  
    line = fp.readline()
    cnt = 1
    while line:
        a.append(line)
        line = fp.readline()

In [17]:
for i in range(len(a)):
    a[i] = a[i].replace('\n','')

In [21]:
import re
from gensim import models, corpora
from nltk import word_tokenize
from nltk.corpus import stopwords

In [22]:
STOPWORDS = stopwords.words('spanish')

def clean_text(text):
    tokenized_text = word_tokenize(text.lower())
    print(tokenized_text)
    cleaned_text = [t for t in tokenized_text if t not in STOPWORDS and re.match('[a-zA-Z\-][a-zA-Z\-]{2,}', t)]
    return cleaned_text

In [23]:
tokenized_data = []
for text in a:
    tokenized_data.append(clean_text(text))

['cuántos', 'minutos', 'tiene', 'una', 'hora', 'y', 'un', 'día']
['cuántas', 'patas', 'tiene', 'una', 'araña']
['cuál', 'es', 'el', 'río', 'más', 'caudaloso', 'del', 'mundo']
['cada', 'cuántos', 'años', 'tenemos', 'un', 'año', 'bisiesto']
['cuántos', 'meses', 'tienen', '28', 'días']
['qué', 'es', 'un', 'siglo']
['quién', 'fue', 'cleopatra']
['qué', 'planeta', 'es', 'el', 'más', 'cercano', 'al', 'sol']
['cuál', 'es', 'la', 'montaña', 'más', 'alta', 'en', 'la', 'actualidad']
['que', 'nombre', 'tiene', 'el', 'sonido', 'que', 'hace', 'una', 'oveja']
['en', 'qué', 'ciudad', 'y', 'en', 'qué', 'país', 'se', 'encuentra', 'la', 'torre', 'eiffel']
['para', 'qué', 'sirven', 'las', 'arterias', 'y', 'las', 'venas']
['qué', 'es', 'un', 'delta']
['si', 'alguien', 'de', 'españa', 'habla', 'español', ',', 'alguien', 'de', 'portugal', 'portugués', 'y', 'alguien', 'de', 'francia', 'francés', '.', 'qué', 'habla', 'alguien', 'de', 'brasil']
['qué', 'huesos', 'encontramos', 'en', 'el', 'antebrazo']
['qué', 

In [24]:
dictionary = corpora.Dictionary(tokenized_data)

In [25]:
corpus = [dictionary.doc2bow(text) for text in tokenized_data]

In [30]:
NUM_TOPICS = 50

In [31]:
lda_model = models.LdaModel(corpus=corpus, num_topics=NUM_TOPICS, id2word=dictionary)

In [32]:
lsi_model = models.LsiModel(corpus=corpus, num_topics=NUM_TOPICS, id2word=dictionary)

In [33]:
print("LDA Model:")
 
for idx in range(NUM_TOPICS):
    # Print the first 10 most representative topics
    print("Topic #%s:" % idx, lda_model.print_topic(idx, 10))
print("=" * 20)
 
print("LSI Model:")
 
for idx in range(NUM_TOPICS):
    # Print the first 10 most representative topics
    print("Topic #%s:" % idx, lsi_model.print_topic(idx, 10))

print("=" * 20)

LDA Model:
Topic #0: 0.194*"alguien" + 0.097*"habla" + 0.049*"españa" + 0.049*"francés" + 0.049*"español" + 0.049*"cristóbal" + 0.049*"llamaban" + 0.049*"tres" + 0.049*"carabelas" + 0.049*"brasil"
Topic #1: 0.231*"manzanas" + 0.116*"amigo" + 0.116*"mejor" + 0.116*"doy" + 0.116*"dado" + 0.002*"llamaban" + 0.002*"carabelas" + 0.002*"colón" + 0.002*"cristóbal" + 0.002*"montes"
Topic #2: 0.080*"tipo" + 0.080*"huesos" + 0.080*"encontramos" + 0.080*"clasificamos" + 0.080*"piano" + 0.080*"antebrazo" + 0.080*"reinos" + 0.080*"instrumento" + 0.080*"seres" + 0.080*"vivos"
Topic #3: 0.131*"palabra" + 0.131*"equivale" + 0.131*"tiempos" + 0.131*"blanca" + 0.131*"abecedario" + 0.003*"dado" + 0.003*"llamaban" + 0.003*"tres" + 0.003*"cuadrado" + 0.003*"suman"
Topic #4: 0.177*"tres" + 0.177*"verbales" + 0.177*"modos" + 0.003*"suman" + 0.003*"colón" + 0.003*"cristóbal" + 0.003*"llamaban" + 0.003*"urales" + 0.003*"cuadrado" + 0.003*"doy"
Topic #5: 0.177*"tipo" + 0.177*"palabra" + 0.177*"aquí" + 0.003*"cr

In [45]:
text = "Teresa es una mona"
bow = dictionary.doc2bow(clean_text(text))

['teresa', 'es', 'una', 'mona']


In [46]:
print(lsi_model[bow])

[(6, 0.35616393321370693), (29, 0.356163933213707), (39, -0.19953425606749556), (49, 0.1995342560674955)]


In [36]:
print(lda_model[bow])

[(0, 0.02), (1, 0.02), (2, 0.02), (3, 0.02), (4, 0.02), (5, 0.02), (6, 0.02), (7, 0.02), (8, 0.02), (9, 0.02), (10, 0.02), (11, 0.02), (12, 0.02), (13, 0.02), (14, 0.02), (15, 0.02), (16, 0.02), (17, 0.02), (18, 0.02), (19, 0.02), (20, 0.02), (21, 0.02), (22, 0.02), (23, 0.02), (24, 0.02), (25, 0.02), (26, 0.02), (27, 0.02), (28, 0.02), (29, 0.02), (30, 0.02), (31, 0.02), (32, 0.02), (33, 0.02), (34, 0.02), (35, 0.02), (36, 0.02), (37, 0.02), (38, 0.02), (39, 0.02), (40, 0.02), (41, 0.02), (42, 0.02), (43, 0.02), (44, 0.02), (45, 0.02), (46, 0.02), (47, 0.02), (48, 0.02), (49, 0.02)]


# Gensim

In [48]:
from gensim import similarities
 
lda_index = similarities.MatrixSimilarity(lda_model[corpus])
 
# Let's perform some queries
similarities = lda_index[lda_model[bow]]
# Sort the similarities
similarities = sorted(enumerate(similarities), key=lambda item: -item[1])
 
# Top most similar documents:
print(similarities[:10])
# [(104, 0.87591344), (178, 0.86124849), (31, 0.8604598), (77, 0.84932965), (85, 0.84843522), (135, 0.84421808), (215, 0.84184396), (353, 0.84038532), (254, 0.83498049), (13, 0.82832891)]
 
# Let's see what's the most similar document
document_id, similarity = similarities[0]
print(a[document_id][:1000])

[(33, 1.0), (49, 1.0), (0, 0.0), (1, 0.0), (2, 0.0), (3, 0.0), (4, 0.0), (5, 0.0), (6, 0.0), (7, 0.0)]
Qué son los montes Urales


# Sklearn

In [53]:
from sklearn.decomposition import NMF, LatentDirichletAllocation, TruncatedSVD
from sklearn.feature_extraction.text import CountVectorizer
 
NUM_TOPICS = 5
 
vectorizer = CountVectorizer(min_df=5, max_df=0.9, 
                             stop_words='english', lowercase=True, 
                             token_pattern='[a-zA-Z\-][a-zA-Z\-]{2,}')
data_vectorized = vectorizer.fit_transform(a)
 
# Build a Latent Dirichlet Allocation Model
lda_model = LatentDirichletAllocation(n_topics=NUM_TOPICS, max_iter=10, learning_method='online')
lda_Z = lda_model.fit_transform(data_vectorized)
print(lda_Z.shape)  # (NO_DOCUMENTS, NO_TOPICS)
 
# Build a Non-Negative Matrix Factorization Model
nmf_model = NMF(n_components=NUM_TOPICS)
nmf_Z = nmf_model.fit_transform(data_vectorized)
print(nmf_Z.shape)  # (NO_DOCUMENTS, NO_TOPICS)
 
# Build a Latent Semantic Indexing Model
lsi_model = TruncatedSVD(n_components=NUM_TOPICS)
lsi_Z = lsi_model.fit_transform(data_vectorized)
print(lsi_Z.shape)  # (NO_DOCUMENTS, NO_TOPICS)
 
 
# Let's see how the first document in the corpus looks like in different topic spaces
print(lda_Z[0])
print(nmf_Z[0])
print(lsi_Z[0])

(50, 5)
(50, 5)
(50, 5)
[0.06686472 0.06668268 0.06682066 0.06753247 0.73209946]
[0.00000000e+00 3.66994992e-06 6.43835757e-01 0.00000000e+00
 6.50419076e-01]
[0.08875131 0.78336724 1.11605757 0.31196995 0.09518684]


/home/bitzer/tutorial/lib/python3.6/site-packages/sklearn/decomposition/online_lda.py:314: DeprecationWarning: n_topics has been renamed to n_components in version 0.19 and will be removed in 0.21
  DeprecationWarning)


In [54]:
def print_topics(model, vectorizer, top_n=10):
    for idx, topic in enumerate(model.components_):
        print("Topic %d:" % (idx))
        print([(vectorizer.get_feature_names()[i], topic[i])
                        for i in topic.argsort()[:-top_n - 1:-1]])
 
print("LDA Model:")
print_topics(lda_model, vectorizer)
print("=" * 20)
 
print("NMF Model:")
print_topics(nmf_model, vectorizer)
print("=" * 20)
 
print("LSI Model:")
print_topics(lsi_model, vectorizer)
print("=" * 20)

LDA Model:
Topic 0:
[('que', 0.4463442542014514), ('una', 0.37654181091009176), ('les', 0.3717259892284743), ('ntos', 0.3551304972014196), ('los', 0.3443210496308527), ('son', 0.31874574501414804)]
Topic 1:
[('los', 8.820770704299747), ('son', 5.189595318628471), ('les', 4.330604980142768), ('una', 0.3726246112698115), ('que', 0.3434153312676182), ('ntos', 0.3246452006149129)]
Topic 2:
[('los', 0.6128489882214682), ('que', 0.4564037462459979), ('les', 0.3696071771154787), ('una', 0.36704613044849016), ('son', 0.34105833214041953), ('ntos', 0.3386914667618176)]
Topic 3:
[('que', 7.400864861654906), ('una', 3.060134338261891), ('los', 0.49773665317168453), ('son', 0.45052762321637807), ('ntos', 0.3994584845461781), ('les', 0.3661685044548145)]
Topic 4:
[('ntos', 5.138370758103316), ('una', 3.3131406512354475), ('son', 1.1045106404142184), ('les', 0.3823596959104182), ('que', 0.3268264921117001), ('los', 0.31686906464310566)]
NMF Model:
Topic 0:
[('son', 1.314346597934331), ('les', 1.1007

In [59]:
text = "La mona lisa"
x = nmf_model.transform(vectorizer.transform([text]))[0]
print(x)
 

[0. 0. 0. 0. 0.]


In [61]:
from sklearn.metrics.pairwise import euclidean_distances
 
def most_similar(x, Z, top_n=5):
    dists = euclidean_distances(x.reshape(1, -1), Z)
    pairs = enumerate(dists[0])
    most_similar = sorted(pairs, key=lambda item: item[1])[:top_n]
    return most_similar
 
similarities = most_similar(x, nmf_Z)
document_id, similarity = similarities[0]
print(a[document_id][:1000])

Cuál es el río más caudaloso del mundo


# Graficas

In [62]:
import pandas as pd
from bokeh.io import push_notebook, show, output_notebook
from bokeh.plotting import figure
from bokeh.models import ColumnDataSource, LabelSet
output_notebook()

Loading BokehJS ...

In [64]:
svd = TruncatedSVD(n_components=2)
documents_2d = svd.fit_transform(data_vectorized)
 
df = pd.DataFrame(columns=['x', 'y', 'document'])
df['x'], df['y'], df['document'] = documents_2d[:,0], documents_2d[:,1], range(len(a))
 
source = ColumnDataSource(ColumnDataSource.from_df(df))
labels = LabelSet(x="x", y="y", text="document", y_offset=8,
                  text_font_size="8pt", text_color="#555555",
                  source=source, text_align='center')
 
plot = figure(plot_width=600, plot_height=600)
plot.circle("x", "y", size=12, source=source, line_color="black", fill_alpha=0.8)
plot.add_layout(labels)
show(plot, notebook_handle=True)

In [65]:
svd = TruncatedSVD(n_components=2)
words_2d = svd.fit_transform(data_vectorized.T)
 
df = pd.DataFrame(columns=['x', 'y', 'word'])
df['x'], df['y'], df['word'] = words_2d[:,0], words_2d[:,1], vectorizer.get_feature_names()
 
source = ColumnDataSource(ColumnDataSource.from_df(df))
labels = LabelSet(x="x", y="y", text="word", y_offset=8,
                  text_font_size="8pt", text_color="#555555",
                  source=source, text_align='center')
 
plot = figure(plot_width=600, plot_height=600)
plot.circle("x", "y", size=12, source=source, line_color="black", fill_alpha=0.8)
plot.add_layout(labels)
show(plot, notebook_handle=True)

# Drichlet 